# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phoneType.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "messages.PhoneType" do
    value :MOBILE, 0
    value :HOME, 1
    value :WORK, 2
  end
end

module Messages
  PhoneType = Google::Protobuf::DescriptorPool.generated_pool.lookup("messages.PhoneType").enummodule
end
