<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace GPBMetadata;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PhoneNumber::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a790a0c706572736f6e2e70726f746f12086d6573736167657322570a06" .
            "506572736f6e120c0a046e616d65180120012809120a0a02696418022001" .
            "2805120d0a05656d61696c18032001280912240a0570686f6e6518042003" .
            "280b32152e6d657373616765732e50686f6e654e756d626572620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

