<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phoneType.proto

namespace GPBMetadata;

class PhoneType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a500a0f70686f6e65547970652e70726f746f12086d657373616765732a" .
            "2b0a0950686f6e6554797065120a0a064d4f42494c45100012080a04484f" .
            "4d45100112080a04574f524b1002620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

