<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

if (false) {
    /**
     * This class is deprecated. Use Person\PhoneType instead.
     * @deprecated
     */
    class Person_PhoneType {}
}
class_exists(Person\PhoneType::class);
@trigger_error('Person_PhoneType is deprecated and will be removed in the next major release. Use Person\PhoneType instead', E_USER_DEPRECATED);

