<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

if (false) {
    /**
     * This class is deprecated. Use Person\PhoneNumber instead.
     * @deprecated
     */
    class Person_PhoneNumber {}
}
class_exists(Person\PhoneNumber::class);
@trigger_error('Person_PhoneNumber is deprecated and will be removed in the next major release. Use Person\PhoneNumber instead', E_USER_DEPRECATED);

