<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace GPBMetadata;

class Person
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adb010a0c706572736f6e2e70726f746f22c2010a06506572736f6e120c" .
            "0a046e616d65180120012809120a0a026964180220012805120d0a05656d" .
            "61696c18032001280912220a0570686f6e6518042003280b32132e506572" .
            "736f6e2e50686f6e654e756d6265721a3e0a0b50686f6e654e756d626572" .
            "120e0a066e756d626572180120012809121f0a047479706518022001280e" .
            "32112e506572736f6e2e50686f6e6554797065222b0a0950686f6e655479" .
            "7065120a0a064d4f42494c45100012080a04484f4d45100112080a04574f" .
            "524b1002620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

