<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

namespace Person;

/**
 * Protobuf type <code>Person.PhoneType</code>
 */
class PhoneType
{
    /**
     * Generated from protobuf enum <code>MOBILE = 0;</code>
     */
    const MOBILE = 0;
    /**
     * Generated from protobuf enum <code>HOME = 1;</code>
     */
    const HOME = 1;
    /**
     * Generated from protobuf enum <code>WORK = 2;</code>
     */
    const WORK = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PhoneType::class, \Person_PhoneType::class);

