# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phoneNumber.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import phoneType_pb2 as phoneType__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='phoneNumber.proto',
  package='messages',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11phoneNumber.proto\x12\x08messages\x1a\x0fphoneType.proto\"@\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.messages.PhoneTypeb\x06proto3')
  ,
  dependencies=[phoneType__pb2.DESCRIPTOR,])




_PHONENUMBER = _descriptor.Descriptor(
  name='PhoneNumber',
  full_name='messages.PhoneNumber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='messages.PhoneNumber.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='messages.PhoneNumber.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=112,
)

_PHONENUMBER.fields_by_name['type'].enum_type = phoneType__pb2._PHONETYPE
DESCRIPTOR.message_types_by_name['PhoneNumber'] = _PHONENUMBER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhoneNumber = _reflection.GeneratedProtocolMessageType('PhoneNumber', (_message.Message,), dict(
  DESCRIPTOR = _PHONENUMBER,
  __module__ = 'phoneNumber_pb2'
  # @@protoc_insertion_point(class_scope:messages.PhoneNumber)
  ))
_sym_db.RegisterMessage(PhoneNumber)


# @@protoc_insertion_point(module_scope)
